import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import Link from "next/link";
import {Button} from "@/components/ui/button";
import Home from "@/app/page";
import {ThemeProvider} from "@/components/theme-provider";
import {ModeToggle} from "@/components/mode-toggle";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: {
        template: "%s | mysite", // それぞれのページでmetadataのtitleを設定することで%sに代入される．
        default: "mysite",
    },
    description: "Generated by create next app",
};

const navItems = [
    {label: "Home", to: "/"},
    {label: "About", to: "/about"},
    {label: "Contact", to: "/contact"},
]

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja" suppressHydrationWarning={true}>
        {/*inter.classNameはnextに既存のgooglefontを取得する*/}
        {/*cnメソッドでmin-h-dvhを追加する．-> min-h-fullだとブラウザの枠の大きさがスクロール時に変わるとレイアウトが崩れる*/}
        <body className={cn(inter.className, "min-h-dvh")}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
        <header className="container h-16 flex items-center border-b justify-between">
            <h1 className="font-bold">LOGO</h1>
            <ul className="flex items-center flex-wrap gap-4">
                {navItems.map((navItem) => (
                    <li key={navItem.label}>
                        <Button variant={"ghost"} asChild>
                            <Link href={navItem.to}>{navItem.label}</Link>
                        </Button>
                    </li>))}
            </ul>
            <ModeToggle/>
        </header>

        {children}

        {/*containerをクラス名に指定することで全体的に左右の余白ができる!!*/}
        {/*
        footerを一番下に固定する方法
            親要素にmin-h-dvh
            fotterにsticky top-fullを追加
        */}
        <footer className="container sticky top-full h-16 items-center flex border-t py-20">
            <p>&copy; ouias</p>
        </footer>
        </ThemeProvider>
        </body>
        </html>
    );
}
